In [6]:
import pandas as pd

In [7]:
s = pd.Series([1, 2, 3, 4, 5], index=["A", "B", "C","D","E"])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [8]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']

In [9]:
df = pd.DataFrame(data, columns=['col1','col2','col3'])
df
display(df)
df.columns=['id','sal','dep']
df.index=['r1','r2','r3','r4']
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

    id  sal  dep
r1   1  444  abc
r2   2  555  def
r3   3  666  ghi
r4   4  444  xyz

In [10]:
df.dtypes

id     int64
sal    int64
dep      str
dtype: object

In [11]:
df['dep'].dtype

In [12]:
df.dep.dtype

In [13]:
df['dep'] = df['dep'].astype('category')

In [14]:
df.dtypes

id        int64
sal       int64
dep    category
dtype: object

In [15]:
col_cat = ['id','sal']
df[col_cat] = df[col_cat].astype('category')

In [16]:
df.dtypes

id     category
sal    category
dep    category
dtype: object

In [18]:
df.head

<bound method NDFrame.head of    id  sal  dep
r1  1  444  abc
r2  2  555  def
r3  3  666  ghi
r4  4  444  xyz>

In [19]:
df.tail

<bound method NDFrame.tail of    id  sal  dep
r1  1  444  abc
r2  2  555  def
r3  3  666  ghi
r4  4  444  xyz>

In [21]:
classfication=df.col2.unique()
type(classfication)

AttributeError: 'DataFrame' object has no attribute 'col2'

In [ ]:
def get_range(df)