In [1]:
import pandas as pd

In [5]:
s = pd.Series([1, 2, 3, 4, 5], index=["A", "B", "C","D","E"])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [ ]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']

In [24]:
df = pd.DataFrame(data, columns=['col1','col2','col3'])
df
display(df)
df.columns=['id','sal','dep']
df.index=['r1','r2','r3','r4']
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

    id  sal  dep
r1   1  444  abc
r2   2  555  def
r3   3  666  ghi
r4   4  444  xyz

In [ ]:
df.dtypes

id     int64
sal    int64
dep      str
dtype: object

In [26]:
df['dep'].dtype

In [28]:
df.dep.dtype

In [29]:
df['dep'] = df['dep'].astype('category')

In [30]:
df.dtypes

id        int64
sal       int64
dep    category
dtype: object

In [31]:
col_cat = ['id','sal']
df[col_cat] = df[col_cat].astype('category')

In [32]:
df.dtypes

id     category
sal    category
dep    category
dtype: object